# =====================================================
# IAUTOMATE UPDATE
# =====================================================
- name: Update iautomate status
  uri:
    url: "http://10.224.11.147:8080/v2/runbooks/orgentityid/1/updaterunbookstatusv2"
    validate_certs: no
    user: "{{ iautomate_user }}"
    password: "{{ iautomate_pass }}"
    method: PUT
    status_code: 200
    return_content: yes
    force_basic_auth: yes
    body_format: json
    body: "{{ lookup('template','status.json.j2') }}"
  delegate_to: localhost
  become: no
  when: iautomate_updates | default(false) | bool